version: "3"
services:
  cups:
    image: ghcr.io/love4taylor/cups-airprint:master
    container_name: cups
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - cups_config:/config
      - cups_services:/services
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
    environment:
      TZ: "Asia/Shanghai"
      CUPSADMIN: "admin"
      CUPSPASSWORD: "password"
volumes:
  cups_config:
  cups_services:
