version: "3"
services:
  cups:
    image: love4taylor/cups-airprint:latest
    container_name: cups
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ~/airprint_data/config:/config
      - ~/airprint_data/services:/services
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=password
